### ISSUE TITLE
school/admin.py

### ISSUE THREAD

**Issue by Hjcom** [ClusterOfGalaxies/eduGalaxy#34]
csv 파일입출력 기능 및 csv import 기능 구현중인데
ModelForm 필드에 모델 필드 안썻다고 씨게 얻어터짐

**Comment by dlwjdghks92** [comment]
https://books.agiliq.com/projects/django-admin-cookbook/en/latest/import.html

참고하셈

**Comment by Hjcom** [comment]
저거 어제 본것같은데 활용할게
