### ISSUE TITLE
school/admin.py 기능 추가

### ISSUE THREAD

**Issue by Hjcom** [ClusterOfGalaxies/eduGalaxy#39]
1. 학교 CSV 파일 관리를 위해 SchoolCSVFile 모델 생성
2. SchoolCsvFileAdmin을 통해 csv파일 관리
- csv 파일 import 및 업로드 구현
- 현재 저장한 파일 read까지 구현

**Comment by dlwjdghks92** [comment]
확인했고, 코멘트남김
