### ISSUE TITLE
ClusterOfGalaxies/eduGalaxy: jhlee <- dlwjdghks92/eduGalaxy: master

### ISSUE THREAD

**Issue by dlwjdghks92** [ClusterOfGalaxies/eduGalaxy#44]
1) UserPost, AdminPost 모델 초안 생성,
    - EduUser에 외래키 두지 않고 초기 계획대로 각 포스트모델에 EduUser외래키 둠,
    - AdminPost에 logo 필드 CharField로 둠. 이미지 자체를 저장하면 병목현상이 발생 한다해서 일단 이미지 파일명만 저장하는 방향으로 생각중

2) my.conf, secrets.json file path 설정변경
/keys 디렉터리에 넣어두는걸로 일단 설정해놓음 상의 필요.

**Comment by dlwjdghks92** [comment]
풀리퀘스트 모르고 햅버렸음 
커밋 로그 보셈

**Comment by Hjcom** [comment]
/keys 디렉토리에 secret 파일 이동 시킴
모델은 토요일 회의 내용처럼 변경 예정
