### ISSUE TITLE
ClusterOfGalaxies/eduGalaxy: Han←Hjcom/eduGalaxy: master

### ISSUE THREAD

**Issue by Hjcom** [ClusterOfGalaxies/eduGalaxy#59]
1. school/models.py 수정
♠ views.py 모델에 맞게 수정
♠ 주석처리 : forms, admin

2. user/models.py 수정
♠ 주석처리 : forms, admin, mixins, urls(부분), validators, views
♠ settings.py : auth_model 수정

**Comment by dlwjdghks92** [comment]
school/models.py 에서 Post class  원투원필드중에 school_info 로 할건지 info로 할건지 정하자
https://github.com/ClusterOfGalaxies/eduGalaxy/commit/9aae47363965f52cd1b1600e5b0037542e9daa09#r34647183
